### ISSUE TITLE
Task List: Lab #5

### ISSUE THREAD

**Issue by apurbaanik** [apurbaanik/binarySearchTreePlaylist#1]
Task List:
- [x] Create a repository
- [x] Add binarySearchTreePlaylist.java
- [x] Create a README file with a description.
- [x] Add the input and output files.
- [x] Submit the link in MS Teams.
